# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bio-gngm"
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan MacLean"]
  s.date = "2012-03-19"
  s.description = "Identify causative mutations in a model genome from NGS reads using the NGM method."
  s.email = "maclean.daniel@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bio-gngm.gemspec",
    "doc/Bio.html",
    "doc/Bio/DB.html",
    "doc/Bio/DB/Pileup.html",
    "doc/Bio/DB/Vcf.html",
    "doc/Bio/Util.html",
    "doc/Bio/Util/Gngm.html",
    "doc/LICENSE_txt.html",
    "doc/_index.html",
    "doc/class_list.html",
    "doc/created.rid",
    "doc/css/common.css",
    "doc/css/full_list.css",
    "doc/css/style.css",
    "doc/doc/created.rid",
    "doc/file_list.html",
    "doc/frames.html",
    "doc/images/add.png",
    "doc/images/bands.png",
    "doc/images/brick.png",
    "doc/images/brick_link.png",
    "doc/images/bug.png",
    "doc/images/bullet_black.png",
    "doc/images/bullet_toggle_minus.png",
    "doc/images/bullet_toggle_plus.png",
    "doc/images/date.png",
    "doc/images/delete.png",
    "doc/images/find.png",
    "doc/images/loadingAnimation.gif",
    "doc/images/macFFBgHack.png",
    "doc/images/package.png",
    "doc/images/page_green.png",
    "doc/images/page_white_text.png",
    "doc/images/page_white_width.png",
    "doc/images/plugin.png",
    "doc/images/ruby.png",
    "doc/images/signal.png",
    "doc/images/tag_blue.png",
    "doc/images/tag_green.png",
    "doc/images/threads.png",
    "doc/images/transparent.png",
    "doc/images/wrench.png",
    "doc/images/wrench_orange.png",
    "doc/images/zoom.png",
    "doc/index.html",
    "doc/js/app.js",
    "doc/js/darkfish.js",
    "doc/js/full_list.js",
    "doc/js/jquery.js",
    "doc/js/navigation.js",
    "doc/js/search.js",
    "doc/js/search_index.js",
    "doc/js/searcher.js",
    "doc/lib/bio-gngm_rb.html",
    "doc/lib/bio/util/bio-gngm_rb.html",
    "doc/method_list.html",
    "doc/rdoc.css",
    "doc/table_of_contents.html",
    "examples/.DS_Store",
    "examples/make_histograms.rb",
    "examples/make_threads.rb",
    "examples/make_threads_isize.rb",
    "examples/use_indels.rb",
    "lib/bio-gngm.rb",
    "lib/bio/util/bio-gngm.rb",
    "scripts/get_subseq.rb",
    "scripts/make_histograms_laerfyve.rb",
    "scripts/make_histograms_laerfyve_stitched.rb",
    "scripts/make_threads_isize_laerfyfe.rb",
    "scripts/make_threads_unmapped_laerfyfe.rb",
    "scripts/make_threads_unmapped_laerfyfe_pseudo.rb",
    "scripts/make_threads_unmapped_simulation.rb",
    "scripts/make_threads_unmapped_simulation_immediate_region.rb",
    "scripts/optimise_freq_window_size.rb",
    "stitched_contigs.zip",
    "test/data/ids2.txt",
    "test/data/sorted.bam",
    "test/data/test",
    "test/data/test.bam",
    "test/data/test.fa",
    "test/data/test.fai",
    "test/data/test.sai",
    "test/data/test.tam",
    "test/data/test_chr.fasta",
    "test/data/test_chr.fasta.amb",
    "test/data/test_chr.fasta.ann",
    "test/data/test_chr.fasta.bwt",
    "test/data/test_chr.fasta.fai",
    "test/data/test_chr.fasta.pac",
    "test/data/test_chr.fasta.rbwt",
    "test/data/test_chr.fasta.rpac",
    "test/data/test_chr.fasta.rsa",
    "test/data/test_chr.fasta.sa",
    "test/data/testu.bam",
    "test/data/testu.bam.bai",
    "test/helper.rb",
    "test/test_bio-gngm.rb"
  ]
  s.homepage = "http://github.com/danmaclean/bioruby-gngm"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Next-Generation Mapping of Mutations"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, [">= 1.4.2"])
      s.add_runtime_dependency(%q<bio-samtools>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<rinruby>, [">= 2.0.2"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<bio>, [">= 1.4.2"])
      s.add_development_dependency(%q<bio-samtools>, [">= 0.5.0"])
      s.add_development_dependency(%q<rinruby>, [">= 2.0.2"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<bio>, [">= 1.4.2"])
      s.add_dependency(%q<bio-samtools>, [">= 0.5.0"])
      s.add_dependency(%q<rinruby>, [">= 2.0.2"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bio>, [">= 1.4.2"])
      s.add_dependency(%q<bio-samtools>, [">= 0.5.0"])
      s.add_dependency(%q<rinruby>, [">= 2.0.2"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<bio>, [">= 1.4.2"])
    s.add_dependency(%q<bio-samtools>, [">= 0.5.0"])
    s.add_dependency(%q<rinruby>, [">= 2.0.2"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bio>, [">= 1.4.2"])
    s.add_dependency(%q<bio-samtools>, [">= 0.5.0"])
    s.add_dependency(%q<rinruby>, [">= 2.0.2"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

